/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package display;

import extensions.Ket_Noi;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import process.ToanDan;

/**
 *
 * @author ASUS
 */
public class frmKhaiBao extends javax.swing.JInternalFrame {

    Connection conn;
    List<ToanDan> list = new ArrayList<>();

    /**
     * Creates new form frmKhaiBao
     */
    public frmKhaiBao() {
        initComponents();
        conn = Ket_Noi.ket_noi("KhaiBaoYTe");
        if (conn != null) {
            loadDataToList();
            System.out.println("Kết nối thành công");
        } else {
            System.out.println("Lỗi kết nối");
        }
    }

    private void loadDataToList() {
        try {
            String sql = "select * from KhaiBaoToanDan";
            Statement st = conn.createStatement();
            ResultSet rs = st.executeQuery(sql);
            
            while(rs.next()){
                String id = rs.getString("id");
                String nguoidung_id = rs.getString("nguoidung_id");
                String dichuyen = rs.getString("dichuyen");
                String trieuchung = rs.getString("trieuchung");
                String nghinhiem = rs.getString("nghinhiem");
                String nuocbenh = rs.getString("nuocbenh");
                String bieuhien = rs.getString("bieuhien");
                list.add(new ToanDan(id, nguoidung_id, dichuyen, trieuchung, nghinhiem, nuocbenh, bieuhien));   
            }
            st.close();
            rs.close();
            return;
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Lỗi load data khai bao toan dan to list ");
        }
    }
    
    public void them(){
        try {
            String nguoidung_id = frmLogin.ID;
            String dichuyen;
            if(rdoCoDiChuyen.isSelected()){
                dichuyen = "có";
            }else{
                dichuyen = "không";
            }
            String trieuchung;
            if(rdoCoTrieuChung.isSelected()){
                trieuchung = "có";
            }else{
                trieuchung = "không";
            }
            String nghinhiem;
            if(rdoCoNghiNhiem.isSelected()){
                nghinhiem = "có";
            }else{
                nghinhiem = "không";
            }
            String nuocbenh;
            if(rdoCoNuocBenh.isSelected()){
                nuocbenh = "có";
            }else{
                nuocbenh = "không";
            }
            String bieuhien;
            if(rdoCoBieuHien.isSelected()){
                bieuhien = "có";
            }else{
                bieuhien = "không";
            }
            list.add(new ToanDan(nguoidung_id, dichuyen, trieuchung, nghinhiem, nuocbenh, bieuhien));
            //them vao database
            String sql = "insert into KhaiBaoToanDan(nguoidung_id,dichuyen,trieuchung,nghinhiem,nuocbenh,bieuhien)\n"
                    + " values('"+nguoidung_id+"',N'"+dichuyen+"',N'"+trieuchung+"','"+nghinhiem+"','"+nuocbenh+"','"+bieuhien+"')";
            PreparedStatement ps = conn.prepareStatement(sql);
            ps.executeUpdate();
            JOptionPane.showMessageDialog(this, "Thêm thông tin người dùng thành công");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Thêm thông tin người dùng không thành công");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btgDiChuyen = new javax.swing.ButtonGroup();
        btgTrieuChung = new javax.swing.ButtonGroup();
        btgNghiNhiem = new javax.swing.ButtonGroup();
        btgNuocBenh = new javax.swing.ButtonGroup();
        btgBieuHien = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jpnToanDan = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        rdoCoNghiNhiem = new javax.swing.JRadioButton();
        rdoKhongNghiNhiem = new javax.swing.JRadioButton();
        rdoCoNuocBenh = new javax.swing.JRadioButton();
        rdoKhongNuocBenh = new javax.swing.JRadioButton();
        rdoCoBieuHien = new javax.swing.JRadioButton();
        rdoKhongBieuHien = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        rdoCoDiChuyen = new javax.swing.JRadioButton();
        rdoKhongDiChuyen = new javax.swing.JRadioButton();
        rdoCoTrieuChung = new javax.swing.JRadioButton();
        rdoKhongTrieuChung = new javax.swing.JRadioButton();
        btnGui = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jpnNoiDia = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtNgayKhoiHanh = new javax.swing.JTextField();
        txtMaHieuPhuongTien = new javax.swing.JTextField();
        txtPhuongTienDiLai = new javax.swing.JTextField();
        txtNoiDen = new javax.swing.JTextField();
        txtNoiDi = new javax.swing.JTextField();
        rdoCoDiChuyen1 = new javax.swing.JRadioButton();
        rdoKhongDiChuyen1 = new javax.swing.JRadioButton();
        btnGuiNoiDia = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        rdoCoTrieuChung1 = new javax.swing.JRadioButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        rdoCoNghiNhiem1 = new javax.swing.JRadioButton();
        rdoKhongNghiNhiem1 = new javax.swing.JRadioButton();
        rdoCoNuocBenh1 = new javax.swing.JRadioButton();
        rdoKhongNuocBenh1 = new javax.swing.JRadioButton();
        rdoCoBieuHien1 = new javax.swing.JRadioButton();
        rdoKhongBieuHien1 = new javax.swing.JRadioButton();
        jLabel20 = new javax.swing.JLabel();
        rdoKhongTrieuChung1 = new javax.swing.JRadioButton();
        jpnNhapCanh = new javax.swing.JPanel();

        jTabbedPane1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jpnToanDan.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Trong vòng 14 ngày qua, Anh/Chị có đến tỉnh/thành phố, quốc gia/vùng lãnh thổ nào (Có thể đi qua nhiều nơi)");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Trong vòng 14 ngày qua, Anh/Chị có thấy xuất hiện ít nhất 1 trong các dấu hiệu: sốt, ho, khó thở, viêm phổi, đau họng, mệt mỏi không?");

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setForeground(new java.awt.Color(204, 204, 204));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Người bệnh hoặc nghi ngờ, mắc bệnh COVID-19 (*)");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Người từ nước có bệnh COVID-19 (*)");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Người có biểu hiện (Sốt, ho, khó thở , Viêm phổi) (*)");

        rdoCoNghiNhiem.setBackground(new java.awt.Color(204, 204, 204));
        rdoCoNghiNhiem.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        rdoCoNghiNhiem.setText("Có");

        rdoKhongNghiNhiem.setBackground(new java.awt.Color(204, 204, 204));
        rdoKhongNghiNhiem.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        rdoKhongNghiNhiem.setText("Không");
        rdoKhongNghiNhiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoKhongNghiNhiemActionPerformed(evt);
            }
        });

        rdoCoNuocBenh.setBackground(new java.awt.Color(204, 204, 204));
        rdoCoNuocBenh.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        rdoCoNuocBenh.setText("Có");

        rdoKhongNuocBenh.setBackground(new java.awt.Color(204, 204, 204));
        rdoKhongNuocBenh.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        rdoKhongNuocBenh.setText("Không");

        rdoCoBieuHien.setBackground(new java.awt.Color(204, 204, 204));
        rdoCoBieuHien.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        rdoCoBieuHien.setText("Có");

        rdoKhongBieuHien.setBackground(new java.awt.Color(204, 204, 204));
        rdoKhongBieuHien.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        rdoKhongBieuHien.setText("Không");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rdoCoNghiNhiem, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(rdoCoNuocBenh, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(rdoCoBieuHien, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rdoKhongNghiNhiem, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(rdoKhongNuocBenh, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(rdoKhongBieuHien, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(rdoCoNghiNhiem)
                    .addComponent(rdoKhongNghiNhiem))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(rdoCoNuocBenh)
                    .addComponent(rdoKhongNuocBenh))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(rdoCoBieuHien)
                    .addComponent(rdoKhongBieuHien))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("Trong vòng 14 ngày qua, Anh/Chị có tiếp xúc với ");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("THÔNG TIN KHAI BÁO Y TẾ");

        btgDiChuyen.add(rdoCoDiChuyen);
        rdoCoDiChuyen.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        rdoCoDiChuyen.setText("Có ");

        btgDiChuyen.add(rdoKhongDiChuyen);
        rdoKhongDiChuyen.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        rdoKhongDiChuyen.setText("Không");

        rdoCoTrieuChung.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        rdoCoTrieuChung.setText("Có");

        rdoKhongTrieuChung.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        rdoKhongTrieuChung.setText("Không");

        btnGui.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnGui.setText("Gửi");
        btnGui.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuiActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("( PHÒNG CHỐNG DỊCH COVID-19 )");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 0, 0));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Khuyến cáo: Khai báo thông tin sai là vi phạm pháp luật Việt Nam và có thể xử lý hình sự");

        javax.swing.GroupLayout jpnToanDanLayout = new javax.swing.GroupLayout(jpnToanDan);
        jpnToanDan.setLayout(jpnToanDanLayout);
        jpnToanDanLayout.setHorizontalGroup(
            jpnToanDanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jpnToanDanLayout.createSequentialGroup()
                .addGroup(jpnToanDanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpnToanDanLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jpnToanDanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rdoCoDiChuyen)
                            .addComponent(rdoCoTrieuChung))
                        .addGap(18, 18, 18)
                        .addGroup(jpnToanDanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rdoKhongDiChuyen, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(rdoKhongTrieuChung, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(jpnToanDanLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(156, 156, 156)
                        .addComponent(btnGui, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpnToanDanLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jpnToanDanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel6))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jpnToanDanLayout.createSequentialGroup()
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 1033, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jpnToanDanLayout.setVerticalGroup(
            jpnToanDanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnToanDanLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel9)
                .addGap(51, 51, 51)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpnToanDanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdoCoDiChuyen)
                    .addComponent(rdoKhongDiChuyen))
                .addGap(27, 27, 27)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpnToanDanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdoCoTrieuChung)
                    .addComponent(rdoKhongTrieuChung))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 107, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addGroup(jpnToanDanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpnToanDanLayout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnToanDanLayout.createSequentialGroup()
                        .addComponent(btnGui, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(88, 88, 88))))
        );

        jTabbedPane1.addTab("Khai báo toàn dân", jpnToanDan);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("Phương tiện đi lại");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setText("Mã hiệu phương tiện");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setText("Nơi đi");

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setText("Nơi đến");

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setText("Ngày khởi hành");

        btgDiChuyen.add(rdoCoDiChuyen1);
        rdoCoDiChuyen1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        rdoCoDiChuyen1.setText("Có ");

        btgDiChuyen.add(rdoKhongDiChuyen1);
        rdoKhongDiChuyen1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        rdoKhongDiChuyen1.setText("Không");

        btnGuiNoiDia.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnGuiNoiDia.setText("Gửi");
        btnGuiNoiDia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuiNoiDiaActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel15.setText("Trong vòng 14 ngày qua, Anh/Chị có đến tỉnh/thành phố, quốc gia/vùng lãnh thổ nào (Có thể đi qua nhiều nơi)");

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel16.setText("Trong vòng 14 ngày qua, Anh/Chị có thấy xuất hiện ít nhất 1 trong các dấu hiệu: sốt, ho, khó thở, viêm phổi, đau họng, mệt mỏi không?");

        rdoCoTrieuChung1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        rdoCoTrieuChung1.setText("Có");

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setForeground(new java.awt.Color(204, 204, 204));

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel17.setText("Người bệnh hoặc nghi ngờ, mắc bệnh COVID-19 (*)");

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel18.setText("Người từ nước có bệnh COVID-19 (*)");

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel19.setText("Người có biểu hiện (Sốt, ho, khó thở , Viêm phổi) (*)");

        rdoCoNghiNhiem1.setBackground(new java.awt.Color(204, 204, 204));
        rdoCoNghiNhiem1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        rdoCoNghiNhiem1.setText("Có");

        rdoKhongNghiNhiem1.setBackground(new java.awt.Color(204, 204, 204));
        rdoKhongNghiNhiem1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        rdoKhongNghiNhiem1.setText("Không");
        rdoKhongNghiNhiem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoKhongNghiNhiem1ActionPerformed(evt);
            }
        });

        rdoCoNuocBenh1.setBackground(new java.awt.Color(204, 204, 204));
        rdoCoNuocBenh1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        rdoCoNuocBenh1.setText("Có");

        rdoKhongNuocBenh1.setBackground(new java.awt.Color(204, 204, 204));
        rdoKhongNuocBenh1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        rdoKhongNuocBenh1.setText("Không");

        rdoCoBieuHien1.setBackground(new java.awt.Color(204, 204, 204));
        rdoCoBieuHien1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        rdoCoBieuHien1.setText("Có");

        rdoKhongBieuHien1.setBackground(new java.awt.Color(204, 204, 204));
        rdoKhongBieuHien1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        rdoKhongBieuHien1.setText("Không");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17)
                    .addComponent(jLabel18)
                    .addComponent(jLabel19))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rdoCoNghiNhiem1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(rdoCoNuocBenh1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(rdoCoBieuHien1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rdoKhongNghiNhiem1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(rdoKhongNuocBenh1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(rdoKhongBieuHien1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(rdoCoNghiNhiem1)
                    .addComponent(rdoKhongNghiNhiem1))
                .addGap(29, 29, 29)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(rdoCoNuocBenh1)
                    .addComponent(rdoKhongNuocBenh1))
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(rdoCoBieuHien1)
                    .addComponent(rdoKhongBieuHien1))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel20.setText("Trong vòng 14 ngày qua, Anh/Chị có tiếp xúc với ");

        rdoKhongTrieuChung1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        rdoKhongTrieuChung1.setText("Không");

        javax.swing.GroupLayout jpnNoiDiaLayout = new javax.swing.GroupLayout(jpnNoiDia);
        jpnNoiDia.setLayout(jpnNoiDiaLayout);
        jpnNoiDiaLayout.setHorizontalGroup(
            jpnNoiDiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnNoiDiaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpnNoiDiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpnNoiDiaLayout.createSequentialGroup()
                        .addGroup(jpnNoiDiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jpnNoiDiaLayout.createSequentialGroup()
                        .addGroup(jpnNoiDiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpnNoiDiaLayout.createSequentialGroup()
                                .addComponent(txtPhuongTienDiLai, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(jpnNoiDiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel13)
                                    .addGroup(jpnNoiDiaLayout.createSequentialGroup()
                                        .addGroup(jpnNoiDiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtNoiDi, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel12))
                                        .addGap(55, 55, 55)
                                        .addGroup(jpnNoiDiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel14)
                                            .addComponent(txtNgayKhoiHanh, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addComponent(jLabel15)
                            .addGroup(jpnNoiDiaLayout.createSequentialGroup()
                                .addGroup(jpnNoiDiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rdoCoDiChuyen1)
                                    .addComponent(rdoCoTrieuChung1))
                                .addGap(18, 18, 18)
                                .addGroup(jpnNoiDiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rdoKhongDiChuyen1, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(rdoKhongTrieuChung1, javax.swing.GroupLayout.Alignment.TRAILING)))
                            .addGroup(jpnNoiDiaLayout.createSequentialGroup()
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(156, 156, 156)
                                .addComponent(btnGuiNoiDia, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel16)
                            .addComponent(jLabel20)
                            .addGroup(jpnNoiDiaLayout.createSequentialGroup()
                                .addComponent(txtMaHieuPhuongTien, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtNoiDen, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(23, Short.MAX_VALUE))))
        );
        jpnNoiDiaLayout.setVerticalGroup(
            jpnNoiDiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnNoiDiaLayout.createSequentialGroup()
                .addGap(131, 131, 131)
                .addGroup(jpnNoiDiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel12)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jpnNoiDiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPhuongTienDiLai, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNoiDi, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNgayKhoiHanh, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jpnNoiDiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel13))
                .addGap(8, 8, 8)
                .addGroup(jpnNoiDiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMaHieuPhuongTien, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNoiDen, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpnNoiDiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdoCoDiChuyen1)
                    .addComponent(rdoKhongDiChuyen1))
                .addGap(27, 27, 27)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpnNoiDiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdoCoTrieuChung1)
                    .addComponent(rdoKhongTrieuChung1))
                .addGap(18, 18, 18)
                .addComponent(jLabel20)
                .addGap(18, 18, 18)
                .addGroup(jpnNoiDiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnNoiDiaLayout.createSequentialGroup()
                        .addComponent(btnGuiNoiDia, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(77, 77, 77)))
                .addGap(17, 17, 17))
        );

        jTabbedPane1.addTab("Khai báo di chuyển nội địa", jpnNoiDia);

        javax.swing.GroupLayout jpnNhapCanhLayout = new javax.swing.GroupLayout(jpnNhapCanh);
        jpnNhapCanh.setLayout(jpnNhapCanhLayout);
        jpnNhapCanhLayout.setHorizontalGroup(
            jpnNhapCanhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1260, Short.MAX_VALUE)
        );
        jpnNhapCanhLayout.setVerticalGroup(
            jpnNhapCanhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 625, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Khai báo nhập cảnh", jpnNhapCanh);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rdoKhongNghiNhiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoKhongNghiNhiemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdoKhongNghiNhiemActionPerformed

    private void btnGuiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuiActionPerformed
        // TODO add your handling code here:
        them();
    }//GEN-LAST:event_btnGuiActionPerformed

    private void btnGuiNoiDiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuiNoiDiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGuiNoiDiaActionPerformed

    private void rdoKhongNghiNhiem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoKhongNghiNhiem1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdoKhongNghiNhiem1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btgBieuHien;
    private javax.swing.ButtonGroup btgDiChuyen;
    private javax.swing.ButtonGroup btgNghiNhiem;
    private javax.swing.ButtonGroup btgNuocBenh;
    private javax.swing.ButtonGroup btgTrieuChung;
    private javax.swing.JButton btnGui;
    private javax.swing.JButton btnGuiNoiDia;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JPanel jpnNhapCanh;
    private javax.swing.JPanel jpnNoiDia;
    private javax.swing.JPanel jpnToanDan;
    private javax.swing.JRadioButton rdoCoBieuHien;
    private javax.swing.JRadioButton rdoCoBieuHien1;
    private javax.swing.JRadioButton rdoCoDiChuyen;
    private javax.swing.JRadioButton rdoCoDiChuyen1;
    private javax.swing.JRadioButton rdoCoNghiNhiem;
    private javax.swing.JRadioButton rdoCoNghiNhiem1;
    private javax.swing.JRadioButton rdoCoNuocBenh;
    private javax.swing.JRadioButton rdoCoNuocBenh1;
    private javax.swing.JRadioButton rdoCoTrieuChung;
    private javax.swing.JRadioButton rdoCoTrieuChung1;
    private javax.swing.JRadioButton rdoKhongBieuHien;
    private javax.swing.JRadioButton rdoKhongBieuHien1;
    private javax.swing.JRadioButton rdoKhongDiChuyen;
    private javax.swing.JRadioButton rdoKhongDiChuyen1;
    private javax.swing.JRadioButton rdoKhongNghiNhiem;
    private javax.swing.JRadioButton rdoKhongNghiNhiem1;
    private javax.swing.JRadioButton rdoKhongNuocBenh;
    private javax.swing.JRadioButton rdoKhongNuocBenh1;
    private javax.swing.JRadioButton rdoKhongTrieuChung;
    private javax.swing.JRadioButton rdoKhongTrieuChung1;
    private javax.swing.JTextField txtMaHieuPhuongTien;
    private javax.swing.JTextField txtNgayKhoiHanh;
    private javax.swing.JTextField txtNoiDen;
    private javax.swing.JTextField txtNoiDi;
    private javax.swing.JTextField txtPhuongTienDiLai;
    // End of variables declaration//GEN-END:variables
}
